# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'aks-connection'
    azureContainerRegistry: '{"loginServer":"sbxdatamgmtacr.azurecr.io", "id" : "/subscriptions/ee5d1262-9e4b-46ec-8a14-0f5f835f6ac2/resourceGroups/sbx-datamgmt-aks-rg/providers/Microsoft.ContainerRegistry/registries/sbxdatamgmtacr"}'
    imageName: '$(Build.Repository.Name):latest'
- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'aks-connection'
    azureContainerRegistry: '{"loginServer":"sbxdatamgmtacr.azurecr.io", "id" : "/subscriptions/ee5d1262-9e4b-46ec-8a14-0f5f835f6ac2/resourceGroups/sbx-datamgmt-aks-rg/providers/Microsoft.ContainerRegistry/registries/sbxdatamgmtacr"}'
    action: 'Push an image'
    imageName: '$(Build.Repository.Name):latest'